<%@ Page Language="C#" MasterPageFile="~/publico.Master" AutoEventWireup="true" CodeBehind="listaproducto.aspx.cs" Inherits="WebApplication.Escuela.Presentation.listaproducto" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .style4
        {
            width: 114px;
        }
        .style5
        {
            width: 311px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <asp:Label ID="lblTitulo" runat="server" BackColor="Yellow" 
        Font-Size="XX-Large" Text="TIENDA DE REPUESTOS"></asp:Label>
&nbsp;<table style="width:100%;" bgcolor="Black">
        <tr>
            <td class="style4">
                &nbsp;</td>
            <td class="style5" id="ndustria">
                <br />
                <asp:RadioButtonList ID="RadioButtonList1" runat="server" BackColor="Yellow">
                    <asp:ListItem>Por Código</asp:ListItem>
                    <asp:ListItem>Por Descripción</asp:ListItem>
                    <asp:ListItem>Por Precio</asp:ListItem>
                    <asp:ListItem>Todos</asp:ListItem>
                </asp:RadioButtonList>
                <br />
                <asp:DropDownList ID="cmbMarca" runat="server" Height="16px" 
                    onselectedindexchanged="cmbMarca_SelectedIndexChanged" Width="125px">
                </asp:DropDownList>
                &nbsp;
                <asp:Label ID="Label2" runat="server" BackColor="Yellow" Text="Por Marca"></asp:Label>
                <br />
                <br />
                <asp:DropDownList ID="cmbIndustria" runat="server" Height="16px" 
                    onselectedindexchanged="cmbIndustria_SelectedIndexChanged" Width="125px">
                </asp:DropDownList>
                &nbsp;
                <asp:Label ID="Label3" runat="server" BackColor="Yellow" Text="Por Industria"></asp:Label>
                <br />
                <br />
                <asp:TextBox ID="txtParam" runat="server" Width="141px"></asp:TextBox>
                <br />
                <br />
                <asp:Button ID="btnBuscar" runat="server" onclick="btnBuscar_Click" Text="Buscar" 
                    Width="142px" />
                <br />
                <br />
                <asp:Label ID="Label1" runat="server" Font-Size="X-Large"></asp:Label>
                <br />
                <br />
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
        AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
                    AutoGenerateEditButton="True" AutoGenerateSelectButton="True" 
                    BackColor="Yellow" 
                    onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing" 
                    onpageindexchanging="GridView1_PageIndexChanging1" 
                    onselectedindexchanging="GridView1_SelectedIndexChanging" 
                    onselectedindexchanged="GridView1_SelectedIndexChanged">
        <Columns>
            <asp:BoundField DataField="id_repuesto" HeaderText="id_repuesto" />
            <asp:BoundField DataField="codigo" HeaderText="Código" />
            <asp:BoundField DataField="descripcion" HeaderText="Descripción" />
            <asp:BoundField DataField="marca" HeaderText="Marca" />
            <asp:BoundField DataField="Industria" HeaderText="Industria" />
            <asp:BoundField DataField="precio" HeaderText="Precio" />
            <asp:ImageField DataImageUrlField="imagen" HeaderText="Imagen">
                <ControlStyle Height="80px" Width="80px" />
            </asp:ImageField>
            <asp:BoundField DataField="imagen" HeaderText="URL Imagen" />
        </Columns>
    </asp:GridView>
            </td>
            <td>
                &nbsp;</td>
                <td>
                    &nbsp;</td>
        </tr>
        <tr>
            <td class="style4">
                &nbsp;</td>
            <td class="style5">
                <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <br />
            </td>
            <td>
                &nbsp;</td>
                <td>
                    &nbsp;</td>
        </tr>
        </table>
    &nbsp;
</asp:Content>
