<%@ Page Language="C#" MasterPageFile="~/administrador.Master" AutoEventWireup="true" CodeBehind="listarProducto.aspx.cs" Inherits="WebApplication.Escuela.Presentation.listarProducto" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .style4
        {
            width: 114px;
        }
        .style5
        {
            width: 311px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    &nbsp;
    <table style="width:100%;" bgcolor="Black">
        <tr>
            <td class="style4">
                &nbsp;</td>
            <td class="style5" id="ndustria">
                <br />
                <asp:RadioButtonList ID="RadioButtonList1" runat="server" BackColor="Yellow">
                    <asp:ListItem>Por Código</asp:ListItem>
                    <asp:ListItem>Por Descripción</asp:ListItem>
                    <asp:ListItem>Por Precio</asp:ListItem>
                    <asp:ListItem>Todos</asp:ListItem>
                </asp:RadioButtonList>
                <br />
                <asp:DropDownList ID="cmbMarca" runat="server" Height="16px" 
                    onselectedindexchanged="cmbMarca_SelectedIndexChanged" Width="125px">
                </asp:DropDownList>
                &nbsp;
                <asp:Label ID="Label2" runat="server" BackColor="Yellow" Text="Por Marca"></asp:Label>
                <br />
                <br />
                <asp:DropDownList ID="cmbIndustria" runat="server" Height="16px" 
                    onselectedindexchanged="cmbIndustria_SelectedIndexChanged" Width="125px">
                </asp:DropDownList>
                &nbsp;
                <asp:Label ID="Label3" runat="server" BackColor="Yellow" Text="Por Industria"></asp:Label>
                <br />
                <br />
                <asp:TextBox ID="txtParam" runat="server" Width="141px"></asp:TextBox>
                &nbsp;&nbsp;&nbsp;
                <br />
                <br />
                <asp:Button ID="btnBuscar" runat="server" onclick="btnBuscar_Click" Text="Buscar" 
                    Width="142px" />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Label ID="Label1" runat="server" Font-Size="Large" BackColor="Yellow"></asp:Label>
                <br />
                <br />
                <br />
                <br />
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
        AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
                    AutoGenerateEditButton="True" AutoGenerateSelectButton="True" 
                    BackColor="Yellow" onselectedindexchanged="GridView1_SelectedIndexChanged" 
                    onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing" 
                    onpageindexchanging="GridView1_PageIndexChanging1">
        <Columns>
            <asp:BoundField DataField="id_repuesto" HeaderText="id_repuesto" />
            <asp:BoundField DataField="codigo" HeaderText="Código" />
            <asp:BoundField DataField="descripcion" HeaderText="Descripción" />
            <asp:BoundField DataField="marca" HeaderText="Marca" />
            <asp:BoundField DataField="Industria" HeaderText="Industria" />
            <asp:BoundField DataField="precio" HeaderText="Precio" />
            <asp:ImageField DataImageUrlField="imagen" HeaderText="Imagen">
                <ControlStyle Height="80px" Width="80px" />
            </asp:ImageField>
            <asp:BoundField DataField="imagen" HeaderText="URL Imagen" />
        </Columns>
    </asp:GridView>
            </td>
            <td>
                &nbsp;</td>
                <td>
                    &nbsp;</td>
        </tr>
        <tr>
            <td class="style4">
                &nbsp;</td>
            <td class="style5">
                <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Image ID="imgRepuesto" runat="server" Height="138px" Width="109px" />
                <br />
            </td>
            <td>
                &nbsp;</td>
                <td>
                    &nbsp;</td>
        </tr>
        <tr>
            <td class="style4" bgcolor="Yellow">
                CODIGO</td>
            <td class="style5">
                <asp:TextBox ID="txtCodigo" runat="server"></asp:TextBox>
            &nbsp;<asp:TextBox ID="txtId" runat="server" Visible="False"></asp:TextBox>
            </td>
            <td>
                &nbsp;</td>
                <td>
                    &nbsp;</td>
        </tr>
        <tr>
            <td class="style4" bgcolor="Yellow">
                DESCRIPCION</td>
            <td class="style5">
                <asp:TextBox ID="txtDescripcion" runat="server"></asp:TextBox>
            </td>
            <td>
                &nbsp;</td>
                <td>
                    &nbsp;</td>
        </tr>
        <tr>
            <td class="style4" bgcolor="Yellow">
                MARCA</td>
            <td class="style5">
                <asp:TextBox ID="txtMarca" runat="server"></asp:TextBox>
            </td>
            <td>
                &nbsp;</td>
                <td>
                    &nbsp;</td>
        </tr>
        <tr>
            <td class="style4" bgcolor="Yellow">
                INDUSTRIA</td>
            <td class="style5">
                <asp:TextBox ID="txtIndustria" runat="server"></asp:TextBox>
            </td>
            <td>
                &nbsp;</td>
                <td>
                    &nbsp;</td>
        </tr>
        <tr>
            <td class="style4" bgcolor="Yellow">
                PRECIO</td>
            <td class="style5">
                <asp:TextBox ID="txtPrecio" runat="server"></asp:TextBox>
                <asp:TextBox ID="txtURL" runat="server" Visible="False"></asp:TextBox>
            </td>
            <td>
                &nbsp;</td>
                <td>
                    &nbsp;</td>
        </tr>
        <tr>
            <td class="style4" bgcolor="Yellow">
                IMAGEN</td>
            <td class="style5">
                <asp:FileUpload ID="fileUpImag" runat="server" />
            &nbsp;<asp:Label ID="Label4" runat="server" BackColor="Yellow" Font-Size="Large"></asp:Label>
            </td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style4">
                &nbsp;</td>
            <td class="style5">
                <asp:Button ID="btnNuevo" runat="server" onclick="btnNuevo_Click" Text="Nuevo" 
                    Width="127px" />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Button ID="btnCancelar" runat="server" onclick="btnCancelar_Click" 
                    Text="Cancelar" Width="121px" />
                &nbsp;
            </td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style4">
                &nbsp;</td>
            <td class="style5">
                <asp:Button ID="btnGuardar" runat="server" onclick="btnGuardar_Click" 
                    Text="Guardar" Width="129px" Enabled="False" />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Button ID="btnModificar" runat="server" onclick="btnModificar_Click" 
                    Text="Modificar" Width="127px" Enabled="False" />
            </td>
            <td>
                &nbsp;</td>
        </tr>
        </table>
    &nbsp;
</asp:Content>
