<%@ Page Language="C#" MasterPageFile="~/administrador.Master" AutoEventWireup="true" CodeBehind="listarUsuarios.aspx.cs" Inherits="WebApplication.Escuela.Presentation.paginasAdmin.listarUsuarios" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .style3
        {
            width: 136px;
        }
        .style4
        {
        width: 303px;
    }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p>
    <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Label ID="Label3" runat="server" Font-Size="XX-Large" 
            Text="LISTA DE USUARIOS" BackColor="Yellow"></asp:Label>
</p>
<p>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <asp:GridView ID="grdUsuarios" runat="server" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" AutoGenerateSelectButton="True" 
        onrowdeleting="grdUsuarios_RowDeleting" onrowediting="grdUsuarios_RowEditing" 
        onselectedindexchanged="grdUsuarios_SelectedIndexChanged" Width="317px" 
        BackColor="Yellow">
        <EditRowStyle BackColor="Black" BorderColor="Black" BorderStyle="Dotted" 
            ForeColor="Yellow" />
    </asp:GridView>
    <table style="width:100%;" bgcolor="Black">
        <tr>
            <td class="style3">
                &nbsp;</td>
            <td class="style4">
                <asp:Label ID="Label1" runat="server" ForeColor="Black" BackColor="Yellow"></asp:Label>
            </td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" bgcolor="Yellow">
                CI</td>
            <td class="style4">
                <asp:TextBox ID="txtCi" runat="server" style="margin-left: 0px"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
                    ControlToValidate="txtCi" ErrorMessage="Ingrese un CI"></asp:RequiredFieldValidator>
            </td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" bgcolor="Yellow">
                NOMBRE</td>
            <td class="style4">
                <asp:TextBox ID="txtNombre" runat="server" style="margin-left: 0px"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" 
                    ControlToValidate="txtNombre" ErrorMessage="Ingrese nombre"></asp:RequiredFieldValidator>
            </td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" bgcolor="Yellow">
                AP. PATERNO</td>
            <td class="style4">
                <asp:TextBox ID="txtPaterno" runat="server" style="margin-left: 0px"></asp:TextBox>
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" 
                    ControlToValidate="txtPaterno" ErrorMessage="Ingrese ap. paterno"></asp:RequiredFieldValidator>
                                        </td>
            <td>
                <asp:Button ID="btnBuscar" runat="server" onclick="btnBuscar_Click" 
                    Text="Buscar" Width="159px" />
                                        </td>
        </tr>
        <tr>
            <td class="style3" bgcolor="Yellow">
                AP. MATERNO</td>
            <td class="style4">
                <asp:TextBox ID="txtMaterno" runat="server" style="margin-left: 0px"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" 
                    ControlToValidate="txtMaterno" ErrorMessage="Ingrese ap. materno"></asp:RequiredFieldValidator>
            </td>
            <td>
                <asp:TextBox ID="txtPar" runat="server" Width="180px" 
                    ontextchanged="txtPar_TextChanged"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td class="style3" bgcolor="Yellow">
                FECHA NAC.</td>
            <td class="style4">
                <asp:TextBox ID="txtFechaNac" runat="server" style="margin-left: 0px"></asp:TextBox>
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" 
                    ControlToValidate="txtFechaNac" ErrorMessage="Ingrese fecha de nacimiento"></asp:RequiredFieldValidator>
                                        </td>
            <td>
                <asp:RadioButtonList ID="rdoListPar" runat="server" BackColor="Yellow">
                    <asp:ListItem>CI</asp:ListItem>
                    <asp:ListItem>NOMBRE</asp:ListItem>
                    <asp:ListItem>PATERNO</asp:ListItem>
                </asp:RadioButtonList>
                                        </td>
        </tr>
        <tr>
            <td class="style3" bgcolor="Yellow">
                TELEFONO</td>
            <td class="style4">
                <asp:TextBox ID="txtTelefono" runat="server" style="margin-left: 0px"></asp:TextBox>
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator6" runat="server" 
                    ControlToValidate="txtTelefono" ErrorMessage="Ingrese teléfono"></asp:RequiredFieldValidator>
                                        </td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" bgcolor="Yellow">
                DIRECCION</td>
            <td class="style4">
                <asp:TextBox ID="txtDireccion" runat="server" style="margin-left: 0px"></asp:TextBox>
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator7" runat="server" 
                    ControlToValidate="txtDireccion" ErrorMessage="Ingrese dirección"></asp:RequiredFieldValidator>
                                        </td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3" bgcolor="Yellow">
                USUARIO</td>
            <td class="style4">
                <asp:TextBox ID="txtUsuario" runat="server" style="margin-left: 0px"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator8" runat="server" 
                    ControlToValidate="txtUsuario" ErrorMessage="Ingrese usuario"></asp:RequiredFieldValidator>
            </td>
            <td>
                <asp:TextBox ID="txtId" runat="server" Visible="False"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td class="style3" bgcolor="Yellow">
                CONTRASEÑA</td>
            <td class="style4">
                <asp:TextBox ID="txtContraseña" runat="server" style="margin-left: 0px"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator9" runat="server" 
                    ControlToValidate="txtContraseña" ErrorMessage="Ingrese contraseña"></asp:RequiredFieldValidator>
            </td>
            <td>
                <asp:Button ID="btnNuevo" runat="server" onclick="btnNuevo_Click" Text="Nuevo" 
                    Width="154px" />
            </td>
        </tr>
         <tr>
            <td class="style3" bgcolor="Yellow">
                TIPO</td>
            <td class="style4">
                <asp:TextBox ID="txtTipo" runat="server"></asp:TextBox>
             </td>
            <td>                
                <asp:Button ID="btnGuardar" runat="server" onclick="btnGuardar_Click" 
                    Text="Guardar" Visible="False" Width="153px" />
             </td>
        </tr> <tr>
            <td class="style3">
                &nbsp;</td>
            <td class="style4">
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
    </table>
</p>
<p>
    &nbsp;</p>
<p>
</p>
<p>
</p>
<p>
</p>
<p>
</p>
</asp:Content>
